### ISSUE TITLE
Create a layout for all the pages based on the design in Figma.

### ISSUE THREAD

**Issue by arjun-gautam** [okfnepal/widnepal-web#16]
- [x] Home page
- [x] About Us
- [x] Projects
- [x] Resources
- [x] Event
- [x] Blog page
- [x] Contact

**Comment by arjun-gautam** [comment]
Complete the layout for Home page

**Comment by sagargg-zz** [comment]
@arjun-gautam  I think you've already done this. can we close this?

**Comment by arjun-gautam** [comment]
@sagargg Till now only home and blogs have completed. Not all pages have been designed. Let's not close this.

**Comment by arjun-gautam** [comment]
Just updated the description section of this issue. Previous description was a bit absurd.

**Comment by arjun-gautam** [comment]
All page completed. I am opening new issue for sidebar
