### ISSUE TITLE
Create a list of tags for various pages(categories).

### ISSUE THREAD

**Issue by arjun-gautam** [okfnepal/widnepal-web#21]
Currently, for each pages text content is assigned a category for it to be display under certain page. Now creating a list of tags under those category to place the contents under particular section in a page.

**Comment by arjun-gautam** [comment]
Targeted structure:

What has been accomplished?
For contents in "Home" page, category in CMS is "Home"
For contents in "Blog" page, category in CMS is "Blog"
... ... ...

What is new to accomplish?
For about us section in "Home" page, tags is CMS "about_us" and category in CMS is "Home".
For member organizations section in "Home" page, tags is CMS "member_organizations" and category in CMS is "Home".
... ... ...

**Comment by arjun-gautam** [comment]
Completed for few sections in Home page: Sections are: header, about us and member organizations

**Comment by sagargg-zz** [comment]
@arjun-gautam  I think it was already implemented. Could you confirm and close the issue?

**Comment by arjun-gautam** [comment]
Yeah, I am closing it
