### ISSUE TITLE
Bug on content update on home 

### ISSUE THREAD

**Issue by sagargg-zz** [okfnepal/widnepal-web#34]
## Expected Behaviour 
   When i update site description and about us content via home page admin UI. It should display both.

## Current behavior 
When i update site description and about us content via home page admin UI. One of it will be removed even i saved it.  

## Steps to reproduce: 
  1.  Go homepage item on admin UI.
  2. Update site description and save. 
  2. Update about us  and save
  3. You’ll see the site description disappeared. 
  
  
  ## Task
  * [x] Test and confirm whether it's a bug or not. 
  *  [x] Fix if it's a bug. 
  * [x] Let team to test.

**Comment by sagargg-zz** [comment]
@arjun-gautam Just realized i need to add a new item and update the section for each section,  before i  was trying to save on the same item.  It was just confusion.

**Comment by arjun-gautam** [comment]
@sagargg Thanks . Closing this issue.
