### ISSUE TITLE
Image should not show on the blog section on homepage. 

### ISSUE THREAD

**Issue by sagargg-zz** [okfnepal/widnepal-web#35]
It should not show the image content.  I think we can use wp excerpt content here which by default removes image content from the post but not that sure.  

Note that we can also remove scrolls.

<img width="603" alt="Screen Shot 2021-02-21 at 8 29 32 PM" src="https://user-images.githubusercontent.com/11631101/108628525-9092a700-7483-11eb-9b6d-b22fda37c081.png">

**Comment by arjun-gautam** [comment]
I removed the image display
