### ISSUE TITLE
Replace dummy content with genuine content on staging site.

### ISSUE THREAD

**Issue by sagargg-zz** [okfnepal/widnepal-web#36]
Since the development of the site is now about to finish. We can test with genuine content. 

# Acceptance Criteria    
- I can see the content has been replaced with genuine content. 

# Tasks
- [x] replace all dummy content with genuine content. 
- [x] Report Arjun/Sagar if you found bugs while doing that.

# Working Docs

- Link to docs [here](https://docs.google.com/document/d/1Drtq9LOWIFm8UAbu2Ux-qJ9IATu0k0vqNVAoDCyzzX4/edit?usp=sharing).

**Comment by nikeshbalami** [comment]
Guys, I have already updated some of the major content. But I don't know how to update a few.

Have curated everything which goes on the homepage here: https://docs.google.com/document/d/1Drtq9LOWIFm8UAbu2Ux-qJ9IATu0k0vqNVAoDCyzzX4/edit?usp=sharing

Can you guys please check and update things as per docs. Let me know if there is any confusion. cc @arjun-gautam @sagargg

**Comment by arjun-gautam** [comment]
@nikeshbalami you may review and close this one

**Comment by nikeshbalami** [comment]
All the dummy content has been removed. I just updated the resources tab and other basics. All looks good. Thanks @arjun-gautam @sagargg 

**Closing this.**
