### ISSUE TITLE
Fix the error with mail server or nodemailer while submitting contact us form. 

### ISSUE THREAD

**Issue by arjun-gautam** [okfnepal/widnepal-web#45]
554 response code was thrown by mail server on submitting contact form

**Comment by sagargg-zz** [comment]
@arjun-gautam  I've investigated a little and found it is a throwing error below.  
```
event - compiled successfully
Error: No recipients defined
    at SMTPConnection._formatError (/Users/sagarg/Documents/OKNP/widnepal-web/node_modules/nodemailer/lib/smtp-connection/index.js:774:19)
    at SMTPConnection._setEnvelope (/Users/sagarg/Documents/OKNP/widnepal-web/node_modules/nodemailer/lib/smtp-connection/index.js:985:34)
```

I believe the recipient email is not set or passed on nodemailer configuration.  Also, NOTE. `from` always needs to set the same as user email `` (in the case of MS server).

**Comment by arjun-gautam** [comment]
@sagargg 
The error :`Error: No recipients defined` popped because you haven't passed them through environment variables. Once you pass the credentials, the error with `554 response code` will appear.

Create a .env.local file and insert the following
```
  RECEIPIENT_MAIL="user@example.com"
  CONTACT_EMAIL_USER="user@example.com"
  CONTACT_EMAIL_PASSWORD="I am password"
```
The submit the contact form and check the logs

**Comment by arjun-gautam** [comment]
@sagargg But I think this may get fixed once we shift to HTTPS. Not sure, may be. I think HTTPS will work because Gmail configuration showed similar issue when submitting the form from the website: wid.oknp.org but when I tried from localhost I was able to send email.

**Comment by sagargg-zz** [comment]
@arjun-gautam  Okay, we can test it once the SSL implemented.

**Comment by arjun-gautam** [comment]
@sagargg Before that also create the .env.local file in your project directory that I have mentioned above in the comments.

**Comment by sagargg-zz** [comment]
@arjun-gautam  thank you  I'm aware of that.  Actually, I'm receiving an email when i provide a hardcoded recipient email.
