### ISSUE TITLE
Duplicate supported by logos 

### ISSUE THREAD

**Issue by sagargg-zz** [okfnepal/widnepal-web#48]
Remove supported by section from the footer.

<img width="1235" alt="Screen Shot 2021-03-14 at 7 29 31 AM" src="https://user-images.githubusercontent.com/11631101/111054745-06909980-8497-11eb-97bf-5b4ec653b86f.png">

**Comment by arjun-gautam** [comment]
@nikeshbalami @sagargg I removed the logos and only the links looked bad. So I removed that too. Please feedback me.
