### ISSUE TITLE
Move Women in Data Conference page into sub-domain

### ISSUE THREAD

**Issue by nikeshbalami** [okfnepal/widnepal-web#50]
The current link is quite long and difficult to share: https://womenindatanepal.org/event/women-in-data-conference

## Tasks

- [x] More the page into sub-domain: conference.womenindatanepal.org

**Comment by sagargg-zz** [comment]
@nikeshbalami  Can we close this?

**Comment by nikeshbalami** [comment]
Redirect working fine.

**Closing the issue.**
