### ISSUE TITLE
Style enhancement of the Conference page

### ISSUE THREAD

**Issue by nikeshbalami** [okfnepal/widnepal-web#51]
- [x] Use capitalized case in the Title, currently, it's in sentence case.
![image](https://user-images.githubusercontent.com/3656268/111091744-10c89b80-855c-11eb-8b03-68ba29c7523d.png)

- [x] Play with banner fonts and alignment. The current banner looks lame; please play with text alignment. Make the size of Register bigger, make the background more transparent etc etc.
![image](https://user-images.githubusercontent.com/3656268/111091750-17efa980-855c-11eb-9461-63fb837b385e.png)

- [x] Display all speaker and panelist headshot photos in round shape. The current square share looks untidy. Also, try to decrease the font size of the speaker position and organization name.
![image](https://user-images.githubusercontent.com/3656268/111091758-1b833080-855c-11eb-8da4-261e9096a452.png)

- [x] Remove the supporter logo and menu from the footer (only for the conference page) and keep the copyright info only. Also, try to decrease the padding.
![image](https://user-images.githubusercontent.com/3656268/111091766-21791180-855c-11eb-9ead-215be592e058.png)
- [x] Bio looks untidy, maybe reduce the font size or add little weight on the font. (playaround on this section)
<img width="987" alt="Screen Shot 2021-03-15 at 6 35 04 PM" src="https://user-images.githubusercontent.com/11631101/111155923-35089480-85bd-11eb-897a-ce1aed2ca562.png">

**Comment by arjun-gautam** [comment]
@nikeshbalami All complete and closed
